const TOKEN_KEY_NAME = 'token';
const COOKIES_EXPIRE_TIME_MILLISECONDS = 86400 * 1000 * 30; // 30 day
const JWT_EXPIRE_TIME = '30d';

export { TOKEN_KEY_NAME, COOKIES_EXPIRE_TIME_MILLISECONDS, JWT_EXPIRE_TIME };
